In [ ]:
import requests
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": 32.7157,
    "longitude": -117.1611,

    "start_date": "2026-01-01",
    "end_date": "2026-10-20",

    "hourly": [
        "temperature_2m",
        "relative_humidity_2m", # How humid the air is
        "wind_speed_10m", # Wind speed
        "wind_direction_10m",
        "shortwave_radiation",
        "direct_radiation",
        "diffuse_radiation",
        "cloud_cover",
        "precipitation",
        "is_day",
    ],

    "timezone": "UTC",
}

response = requests.get(url, params=params)
response.raise_for_status()  # Raise an error if the request was unsuccessful

data = response.json()
df = pd.DataFrame(data["hourly"])

df['time'] = pd.to_datetime(df['time'],utc=True)

display(df)

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,precipitation,is_day
0,2026-01-01 00:00:00+00:00,15.3,96,5.7,349,14.0,0.0,14.0,100,2.1,1
1,2026-01-01 01:00:00+00:00,15.2,97,3.2,333,2.0,0.0,2.0,100,2.2,0
2,2026-01-01 02:00:00+00:00,15.3,97,2.8,72,0.0,0.0,0.0,100,0.7,0
3,2026-01-01 03:00:00+00:00,15.3,93,8.3,77,0.0,0.0,0.0,100,0.0,0
4,2026-01-01 04:00:00+00:00,15.6,90,6.9,49,0.0,0.0,0.0,100,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
7027,2026-10-20 19:00:00+00:00,24.1,69,8.7,238,682.0,558.0,124.0,52,0.0,1
7028,2026-10-20 20:00:00+00:00,24.1,67,10.0,240,722.0,591.0,131.0,1,0.0,1
7029,2026-10-20 21:00:00+00:00,24.1,64,10.6,238,708.0,619.0,89.0,4,0.0,1
7030,2026-10-20 22:00:00+00:00,23.9,66,8.8,239,603.0,514.0,89.0,5,0.0,1
7031,2026-10-20 23:00:00+00:00,23.4,68,7.1,232,456.0,375.0,81.0,5,0.0,1

In [6]:
# Check the dataset dimensions
print("Shape:", df.shape)

# Check missing values in each column
print("\nMissing values:")
print(df.isna().sum())

# Inspect the last 10 rows
display(df.tail(10))

# Check whether timestamps are duplicated
print(
    "\nDuplicate timestamps:",
    df["time"].duplicated().sum()
)

# Check the first and last timestamps
print("\nFirst timestamp:", df["time"].min())
print("Last timestamp:", df["time"].max())

Shape: (7032, 11)

Missing values:
time                    0
temperature_2m          0
relative_humidity_2m    0
wind_speed_10m          0
wind_direction_10m      0
shortwave_radiation     0
direct_radiation        0
diffuse_radiation       0
cloud_cover             0
precipitation           0
is_day                  0
dtype: int64

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,precipitation,is_day
7022,2026-10-20 14:00:00+00:00,17.4,93,5.6,84,0.0,0.0,0.0,2,0.0,1
7023,2026-10-20 15:00:00+00:00,18.8,84,6.9,83,67.0,41.0,26.0,18,0.0,1
7024,2026-10-20 16:00:00+00:00,21.2,77,4.6,116,246.0,174.0,72.0,16,0.0,1
7025,2026-10-20 17:00:00+00:00,22.9,72,4.0,185,438.0,351.0,87.0,42,0.0,1
7026,2026-10-20 18:00:00+00:00,23.6,70,6.7,226,590.0,484.0,106.0,55,0.0,1
7027,2026-10-20 19:00:00+00:00,24.1,69,8.7,238,682.0,558.0,124.0,52,0.0,1
7028,2026-10-20 20:00:00+00:00,24.1,67,10.0,240,722.0,591.0,131.0,1,0.0,1
7029,2026-10-20 21:00:00+00:00,24.1,64,10.6,238,708.0,619.0,89.0,4,0.0,1
7030,2026-10-20 22:00:00+00:00,23.9,66,8.8,239,603.0,514.0,89.0,5,0.0,1
7031,2026-10-20 23:00:00+00:00,23.4,68,7.1,232,456.0,375.0,81.0,5,0.0,1

Duplicate timestamps: 0

First timestamp: 2026-01-01 00:00:00+00:00
Last timestamp: 2026-10-20 23:00:00+00:00

In [7]:
df.to_csv("open_meteo_weather_2026.csv", index=False)

In [8]:
df

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,precipitation,is_day
0,2026-01-01 00:00:00+00:00,15.3,96,5.7,349,14.0,0.0,14.0,100,2.1,1
1,2026-01-01 01:00:00+00:00,15.2,97,3.2,333,2.0,0.0,2.0,100,2.2,0
2,2026-01-01 02:00:00+00:00,15.3,97,2.8,72,0.0,0.0,0.0,100,0.7,0
3,2026-01-01 03:00:00+00:00,15.3,93,8.3,77,0.0,0.0,0.0,100,0.0,0
4,2026-01-01 04:00:00+00:00,15.6,90,6.9,49,0.0,0.0,0.0,100,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
7027,2026-10-20 19:00:00+00:00,24.1,69,8.7,238,682.0,558.0,124.0,52,0.0,1
7028,2026-10-20 20:00:00+00:00,24.1,67,10.0,240,722.0,591.0,131.0,1,0.0,1
7029,2026-10-20 21:00:00+00:00,24.1,64,10.6,238,708.0,619.0,89.0,4,0.0,1
7030,2026-10-20 22:00:00+00:00,23.9,66,8.8,239,603.0,514.0,89.0,5,0.0,1
7031,2026-10-20 23:00:00+00:00,23.4,68,7.1,232,456.0,375.0,81.0,5,0.0,1

In [9]:
def load_eia_retail_sales() -> pd.DataFrame:
    api_key = os.getenv("EIA_API_KEY")
    if not api_key:
        raise RuntimeError(
            "EIA_API_KEY is not set. Register at https://www.eia.gov/opendata/register.php "
            "and add EIA_API_KEY to .env in the repo root."
        )

    rows = []
    offset = 0
    total = None
    while total is None or offset < total:
        params = [
            ("api_key", api_key),
            ("frequency", "monthly"),
            ("start", START_DATE[:7]),
            ("end", END_DATE[:7]),
            ("facets[stateid][]", EIA_STATE),
            ("sort[0][column]", "period"),
            ("sort[0][direction]", "asc"),
            ("offset", str(offset)),
            ("length", str(EIA_PAGE_SIZE)),
        ]
        params.extend(("data[]", column) for column in EIA_DATA_COLUMNS)
        url = "https://api.eia.gov/v2/electricity/retail-sales/data?" + urlencode(params)
        payload = get_json(url)
        response = payload["response"]
        batch = response.get("data") or []
        total = int(response["total"])
        rows.extend(batch)
        offset += len(batch)
        if not batch:
            break

    frame = pd.DataFrame(rows)
    id_columns = {"period", "stateid", "stateDescription", "sectorid", "sectorName"}
    for column in frame.columns:
        if column in id_columns or str(column).endswith("-units"):
            continue
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
    return frame


eia_retail_sales = load_eia_retail_sales()
print(eia_retail_sales.shape)
eia_retail_sales.head()

NameError: name 'os' is not defined